// <auto-generated />
namespace TMDT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _new_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_new_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202012070703405__new_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
